### ISSUE TITLE
`xml:space="preserve"` is not handled

### ISSUE THREAD

**Issue by Marcisbee** [lowlighter/libs#25]
There is an unhandled case where `xml:space="preserve"` is not taken into account.

Input:
```xml
<t xml:space="preserve">  there are two spaces here  </t>
```

Current output:
```ts
{
  t: {
    "@xml:space": "preserve",
    "#text": "there are two spaces here"
  }
}
```

According to [w3 spec](https://www.w3.org/TR/xml/#sec-white-space) it should instead return something closer to this:
Expectation:
```ts
{
  t: {
    "@xml:space": "preserve",
    "#text": "  there are two spaces here  "
  }
}
```
or this
```ts
{
  t: "  there are two spaces here  "
}
```

**Comment by lowlighter** [comment]
Hi 👋 !

Sorry for the delay, the directive should be supported as expected with the new release.
The output will be like the first result you posted (in order to be consistent with how attributes are currently handled)

We could add support for the later through an option if this is something requested
