### ISSUE TITLE
parse stream

### ISSUE THREAD

**Issue by ethicnology** [lowlighter/libs#6]
Is there a way to parse stream ?

**Comment by lowlighter** [comment]
Currently only `string` is supported, so it is required to read the whole stream first before parsing it.

What's your use case if it's not too indiscret?

**Comment by ethicnology** [comment]
I'm converting OpenStreetMap data to [graph/network](https://en.wikipedia.org/wiki/Graph_theory).
.osm files are using XML so your library help me to manipulate these data into a dict/object.
Currently, i'm testing the process with small data, but in the future i would like to be able to :
```
cat data.osm | deno run map_to_graph.js > output
```

**Comment by lowlighter** [comment]
I think it would need a complete rewrite of the parser unfortunately.

I may give it a shot if I'm motivated enough one day though 🙂

**Comment by ethicnology** [comment]
I just finished my [tool](https://github.com/ethicnology/osmtograph). The input dataset limit is fixed by [Deno.readTextFile](https://doc.deno.land/builtin/stable#Deno.readTextFile) which is around 500Mo.  
Stream parsing, let your lib users bypass this limitation and allow them to process huge input file (>500Mo).

**Comment by ethicnology** [comment]
I bypass the scaling problem by formatting XML file into a new one where each line represent an element.
Then, i can read stdin line by line and parse the line using your lib.
Indeed, I will try your new stream parser as soon as you release it to remove the formatting step :rocket:

**Comment by lowlighter** [comment]
I've got a working support for stream, but unfortunately performance are far worse atm:

|input|v1|v2|v2 + progress logged in stdout|
|-|-|-|-|
|`string`|~7s/mb|~12s/mb|~18s/mb|
|`stream`|N/A|~42s/mb|~53s/mb|

I didn't dig into it that much for now, but probably needs to do some optimization with buffer allocations and check for redundunt ops. It could be also an i/o issue, since the v2 draft use sync ops (to keep consistencies with other data parse/stringify I'd like to keep it sync). 

Will investigate on this
